# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Holder.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Holder(object):
    def setupUi(self, Holder):
        Holder.setObjectName("Holder")
        Holder.resize(960, 540)
        Holder.setMinimumSize(QtCore.QSize(960, 540))

        self.retranslateUi(Holder)
        QtCore.QMetaObject.connectSlotsByName(Holder)

    def retranslateUi(self, Holder):
        _translate = QtCore.QCoreApplication.translate
        Holder.setWindowTitle(_translate("Holder", "StackedWidget"))
