# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alert(object):
    def setupUi(self, Alert):
        Alert.setObjectName("Alert")
        Alert.resize(350, 200)
        Alert.setMaximumSize(QtCore.QSize(350, 200))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Alert)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(Alert)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msg = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.msg.setFont(font)
        self.msg.setStyleSheet("color: red;")
        self.msg.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.msg.setObjectName("msg")
        self.verticalLayout.addWidget(self.msg)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CANCEL = QtWidgets.QPushButton(self.frame_2)
        self.CANCEL.setMinimumSize(QtCore.QSize(0, 30))
        self.CANCEL.setBaseSize(QtCore.QSize(0, 1))
        self.CANCEL.setStyleSheet("")
        self.CANCEL.setObjectName("CANCEL")
        self.horizontalLayout_3.addWidget(self.CANCEL)
        self.YES = QtWidgets.QPushButton(self.frame_2)
        self.YES.setMinimumSize(QtCore.QSize(0, 30))
        self.YES.setObjectName("YES")
        self.horizontalLayout_3.addWidget(self.YES)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(Alert)
        QtCore.QMetaObject.connectSlotsByName(Alert)

    def retranslateUi(self, Alert):
        _translate = QtCore.QCoreApplication.translate
        Alert.setWindowTitle(_translate("Alert", "Dialog"))
        self.msg.setText(_translate("Alert", "You are about to Log Out"))
        self.label.setText(_translate("Alert", "Are You Sure?"))
        self.CANCEL.setText(_translate("Alert", "CANCEL"))
        self.YES.setText(_translate("Alert", "YES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alert = QtWidgets.QDialog()
    ui = Ui_Alert()
    ui.setupUi(Alert)
    Alert.show()
    sys.exit(app.exec_())
