# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Davin Nazhif\Documents\GitHub\pfm\UI\loadingScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadingScreen(object):
    def setupUi(self, loadingScreen):
        loadingScreen.setObjectName("loadingScreen")
        loadingScreen.resize(378, 387)
        self.centralwidget = QtWidgets.QWidget(loadingScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.circularLoading = QtWidgets.QFrame(self.centralwidget)
        self.circularLoading.setGeometry(QtCore.QRect(30, 20, 320, 320))
        self.circularLoading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularLoading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularLoading.setObjectName("circularLoading")
        self.circularProg = QtWidgets.QFrame(self.circularLoading)
        self.circularProg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularProg.setStyleSheet("QFrame{\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(255, 215, 0, 255));\n"
"}\n"
"")
        self.circularProg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProg.setObjectName("circularProg")
        self.circularBG = QtWidgets.QFrame(self.circularLoading)
        self.circularBG.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularBG.setStyleSheet("QFrame{\n"
"    border-radius:150px;\n"
"    background-color: rgb(255, 236, 219);\n"
"}")
        self.circularBG.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularBG.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBG.setObjectName("circularBG")
        self.container = QtWidgets.QFrame(self.circularLoading)
        self.container.setGeometry(QtCore.QRect(25, 25, 270, 270))
        self.container.setStyleSheet("QFrame{\n"
"border-radius: 135px;\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.wePresent = QtWidgets.QLabel(self.container)
        self.wePresent.setGeometry(QtCore.QRect(40, 30, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraLight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wePresent.setFont(font)
        self.wePresent.setStyleSheet("color:rgb(255, 195, 0);\n"
"background-color: none;")
        self.wePresent.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">We Proudly Present</span></p></body></html>")
        self.wePresent.setAlignment(QtCore.Qt.AlignCenter)
        self.wePresent.setObjectName("wePresent")
        self.projectName = QtWidgets.QLabel(self.container)
        self.projectName.setGeometry(QtCore.QRect(40, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.projectName.setFont(font)
        self.projectName.setStyleSheet("color:rgb(255, 195, 0);\n"
"background-color: none;")
        self.projectName.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">$PFM</span></p></body></html>")
        self.projectName.setAlignment(QtCore.Qt.AlignCenter)
        self.projectName.setObjectName("projectName")
        self.percentage = QtWidgets.QLabel(self.container)
        self.percentage.setGeometry(QtCore.QRect(40, 70, 201, 151))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Light")
        font.setPointSize(68)
        font.setBold(False)
        font.setWeight(50)
        self.percentage.setFont(font)
        self.percentage.setStyleSheet("color:rgb(255, 195, 0);\n"
"background-color: none;")
        self.percentage.setText("<html><head/><body><p align=\"center\">0<span style=\" font-size:48pt; vertical-align:sub;\">%</span></p></body></html>")
        self.percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.percentage.setObjectName("percentage")
        self.loading = QtWidgets.QLabel(self.container)
        self.loading.setGeometry(QtCore.QRect(100, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.loading.setFont(font)
        self.loading.setStyleSheet("color:rgb(255, 195, 0);\n"
"background-color: none;")
        self.loading.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Loading...</span></p></body></html>")
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.circularBG.raise_()
        self.circularProg.raise_()
        self.container.raise_()
        loadingScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(loadingScreen)
        QtCore.QMetaObject.connectSlotsByName(loadingScreen)

    def retranslateUi(self, loadingScreen):
        _translate = QtCore.QCoreApplication.translate
        loadingScreen.setWindowTitle(_translate("loadingScreen", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadingScreen = QtWidgets.QMainWindow()
    ui = Ui_loadingScreen()
    ui.setupUi(loadingScreen)
    loadingScreen.show()
    sys.exit(app.exec_())
