# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Davin Nazhif\Documents\GitHub\pfm\UI\Login&Signup\loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 652)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loginFrame = QtWidgets.QFrame(Form)
        self.loginFrame.setMinimumSize(QtCore.QSize(500, 630))
        self.loginFrame.setMaximumSize(QtCore.QSize(700, 700))
        self.loginFrame.setAcceptDrops(False)
        self.loginFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginFrame.setStyleSheet(
            "#loginFrame{\n"
            "background-color: rgb(42, 43, 48);       \n"
            "padding-left: 15px;      \n"
            "padding-right: 15px;       \n"
            "padding-top: 25px;          \n"
            "padding-bottom: 25px;\n"
            "border-radius: 15px;      \n"
            "}\n"
            "QLabel{\n"
            "    padding:5px;\n"
            "}\n"
            "QLineEdit{\n"
            "    height:50px;\n"
            "    padding: 1px 15 px;\n"
            "    background-color: rgb(42, 43, 48);\n"
            "    border: 1px solid rgba(84,86,95,255);\n"
            "    border-radius: 10px;\n"
            "    color:rgb(255, 255, 255);\n"
            "}\n"
            "#signin{\n"
            "    background-color: rgb(254, 221, 59);    \n"
            "    border-radius:5px;\n"
            "    height:50px;\n"
            "}\n"
            "#createAcc{\n"
            "    color:rgb(255, 255, 255);\n"
            "    background-color: rgb(84, 86, 95);\n"
            "    border-radius:15px;\n"
            "    height:30px;\n"
            "}\n"
            "#forgotPw{\n"
            "    background-color:rgb(42,43,48);\n"
            "    color:#808390;\n"
            "border-radius:15px;\n"
            "    height:30px;\n"
            "}"
        )
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.loginFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.inputUsername = QtWidgets.QLineEdit(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.inputUsername.setFont(font)
        self.inputUsername.setObjectName("inputUsername")
        self.gridLayout.addWidget(self.inputUsername, 2, 0, 1, 2)
        self.loginHeader = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(13)
        self.loginHeader.setFont(font)
        self.loginHeader.setObjectName("loginHeader")
        self.gridLayout.addWidget(self.loginHeader, 0, 0, 1, 2)
        self.username = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 0, 1, 2)
        self.signin = QtWidgets.QPushButton(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.signin.setFont(font)
        self.signin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin.setObjectName("signin")
        self.gridLayout.addWidget(self.signin, 6, 0, 1, 2)
        self.inputPw = QtWidgets.QLineEdit(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.inputPw.setFont(font)
        self.inputPw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPw.setObjectName("inputPw")
        self.gridLayout.addWidget(self.inputPw, 4, 0, 1, 2)
        self.password = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 3, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.loginFrame)
        self.frame_2.setStyleSheet("padding:0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.noAcc = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.noAcc.setFont(font)
        self.noAcc.setStyleSheet("padding-left:0px;")
        self.noAcc.setObjectName("noAcc")
        self.horizontalLayout.addWidget(self.noAcc)
        self.createAcc = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.createAcc.setFont(font)
        self.createAcc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createAcc.setObjectName("createAcc")
        self.horizontalLayout.addWidget(self.createAcc)
        self.gridLayout.addWidget(self.frame_2, 8, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.loginFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.forgotPw = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.forgotPw.setFont(font)
        self.forgotPw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgotPw.setObjectName("forgotPw")
        self.horizontalLayout_2.addWidget(self.forgotPw)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.errorMsg = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.errorMsg.setFont(font)
        self.errorMsg.setStyleSheet("color:rgb(42,43,48);\n"
"padding:0px;")
        self.errorMsg.setObjectName("errorMsg")
        self.horizontalLayout_2.addWidget(self.errorMsg)
        self.gridLayout.addWidget(self.frame, 5, 0, 1, 2)
        self.gridLayout_2.addWidget(self.loginFrame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inputUsername.setPlaceholderText(_translate("Form", "Please enter your username..."))
        self.loginHeader.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#fedd3b;\">Take control of your finances.</span><span style=\" font-size:16pt;\"><br/></span><span style=\" font-size:16pt; color:#808390;\">Log in to your PFM account</span></p></body></html>"))
        self.username.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#808390;\">Username</span></p></body></html>"))
        self.signin.setText(_translate("Form", "Sign in"))
        self.inputPw.setPlaceholderText(_translate("Form", "Please enter your password..."))
        self.password.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#808390;\">Password</span></p></body></html>"))
        self.noAcc.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#808390;\">Don\'t Have an Account Yet?</span></p></body></html>"))
        self.createAcc.setText(_translate("Form", "Create"))
        self.forgotPw.setText(_translate("Form", "Forgot Password?"))
        self.errorMsg.setText(_translate("Form", "*Incorrect Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_loginPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
