# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Master.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Master(object):
    def setupUi(self, Master):
        Master.setObjectName("Master")
        Master.resize(767, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\../Assets/UWOGH.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Master.setWindowIcon(icon)
        Master.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Master)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainMenu = QtWidgets.QWidget(self.centralwidget)
        self.mainMenu.setStyleSheet("background-color: #23272A")
        self.mainMenu.setObjectName("mainMenu")
        self.gridLayout = QtWidgets.QGridLayout(self.mainMenu)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainMenu)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.home)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setMaximumSize(QtCore.QSize(200, 200))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("UI\\../Assets/UWOGH.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.label_9 = QtWidgets.QLabel(self.home)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.stackedWidget.addWidget(self.home)
        self.loginsignup = QtWidgets.QWidget()
        self.loginsignup.setObjectName("loginsignup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.loginsignup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.innerstackedWidget = QtWidgets.QStackedWidget(self.loginsignup)
        self.innerstackedWidget.setMinimumSize(QtCore.QSize(630, 700))
        self.innerstackedWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.innerstackedWidget.setObjectName("innerstackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setStyleSheet("")
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginFrame = QtWidgets.QFrame(self.loginPage)
        self.loginFrame.setMinimumSize(QtCore.QSize(500, 630))
        self.loginFrame.setMaximumSize(QtCore.QSize(1000, 700))
        self.loginFrame.setStyleSheet("#loginFrame{\n"
"    background-color: rgb(42, 43, 48);       \n"
"       padding-left: 15px;      \n"
"       padding-right: 20px;       \n"
"    padding-top: 25px;          \n"
"    padding-bottom: 25px;\n"
"    border-radius: 15px;      \n"
"}\n"
"#username, #password{\n"
"    padding-top:25px;\n"
"}\n"
"QLabel{\n"
"    background-color:none;\n"
"    padding:5px;\n"
"}\n"
"QLineEdit{\n"
"    height:50px;\n"
"    padding: 1px 15 px;\n"
"    background-color: rgb(42, 43, 48);\n"
"    border: 1px solid rgba(84,86,95,255);\n"
"    border-radius: 10px;\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"#LI_buttonLI{\n"
"    background-color: rgb(254, 221, 59);    \n"
"    border-radius:5px;\n"
"    height:50px;\n"
"}\n"
"#LI_buttonSignIn{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(84, 86, 95);\n"
"    border-radius:15px;\n"
"    height:30px;\n"
"}\n"
"#LI_buttonForgetPassword{\n"
"    background-color:rgb(42,43,48);\n"
"    color:#808390;\n"
"    border-radius:15px;\n"
"    height:30px;\n"
"}\n"
"#username, #password, #LI_noAcc{\n"
"    color: rgb(128, 131, 144);\n"
"    font-family: Poppins;\n"
"}\n"
"#LI_ErrorMsg{\n"
"    color: rgb(42, 43, 48);\n"
"    font-family: Poppins;\n"
"}\n"
"#frame, #frame_2{\n"
"background-color: rgb(42, 43, 48);\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.loginFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.username = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.gridLayout_4.addWidget(self.username, 1, 0, 1, 1)
        self.password = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout_4.addWidget(self.password, 3, 0, 1, 1)
        self.LI_inputUsername = QtWidgets.QLineEdit(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.LI_inputUsername.setFont(font)
        self.LI_inputUsername.setObjectName("LI_inputUsername")
        self.gridLayout_4.addWidget(self.LI_inputUsername, 2, 0, 1, 1)
        self.LI_inputPassword = QtWidgets.QLineEdit(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.LI_inputPassword.setFont(font)
        self.LI_inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LI_inputPassword.setObjectName("LI_inputPassword")
        self.gridLayout_4.addWidget(self.LI_inputPassword, 4, 0, 1, 1)
        self.LI_buttonLI = QtWidgets.QPushButton(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LI_buttonLI.setFont(font)
        self.LI_buttonLI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LI_buttonLI.setObjectName("LI_buttonLI")
        self.gridLayout_4.addWidget(self.LI_buttonLI, 6, 0, 1, 1)
        self.loginHeader = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(13)
        self.loginHeader.setFont(font)
        self.loginHeader.setObjectName("loginHeader")
        self.gridLayout_4.addWidget(self.loginHeader, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(553, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 7, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.loginFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LI_buttonForgetPassword = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.LI_buttonForgetPassword.setFont(font)
        self.LI_buttonForgetPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LI_buttonForgetPassword.setObjectName("LI_buttonForgetPassword")
        self.horizontalLayout_2.addWidget(self.LI_buttonForgetPassword)
        spacerItem4 = QtWidgets.QSpacerItem(589, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.LI_ErrorMsg = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.LI_ErrorMsg.setFont(font)
        self.LI_ErrorMsg.setStyleSheet("color: rgb(255, 55, 58);")
        self.LI_ErrorMsg.setText("")
        self.LI_ErrorMsg.setObjectName("LI_ErrorMsg")
        self.horizontalLayout_2.addWidget(self.LI_ErrorMsg)
        self.gridLayout_4.addWidget(self.frame, 5, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.loginFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LI_noAcc = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.LI_noAcc.setFont(font)
        self.LI_noAcc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LI_noAcc.setObjectName("LI_noAcc")
        self.horizontalLayout_3.addWidget(self.LI_noAcc)
        self.LI_buttonSignIn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LI_buttonSignIn.setFont(font)
        self.LI_buttonSignIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LI_buttonSignIn.setObjectName("LI_buttonSignIn")
        self.horizontalLayout_3.addWidget(self.LI_buttonSignIn)
        self.gridLayout_4.addWidget(self.frame_2, 8, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.loginFrame)
        self.innerstackedWidget.addWidget(self.loginPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setStyleSheet("QScrollArea {\n"
"    border: 10px solid rgb(42, 43, 48);; /* Set the border color and width */\n"
"    border-radius: 15px; /* Optional: Add some rounding to the corners */\n"
"    background-color:  rgb(42, 43, 48); /* Ensure the background matches your theme */\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #2C2F33;\n"
"    width: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #555;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #2C2F33;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.signupPage.setObjectName("signupPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.signupPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.signupPage)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollBar = QtWidgets.QWidget()
        self.scrollBar.setGeometry(QtCore.QRect(0, 0, 748, 900))
        self.scrollBar.setStyleSheet("")
        self.scrollBar.setObjectName("scrollBar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollBar)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.signupFrame = QtWidgets.QFrame(self.scrollBar)
        self.signupFrame.setMinimumSize(QtCore.QSize(500, 900))
        self.signupFrame.setStyleSheet("#signupFrame{\n"
"    background-color: rgb(42, 43, 48);    \n"
"       padding-left: 5px;      \n"
"       padding-right: 5px;       \n"
"    padding-top: 25px;          \n"
"    padding-bottom: 25px;\n"
"}\n"
"#SI_buttonLogIn{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(84, 86, 95);\n"
"    border-radius:15px;\n"
"    height:30px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(42, 43, 48);\n"
"    padding-left:5px;\n"
"}\n"
"#frame_3{\n"
"    background-color: rgb(42, 43, 48);\n"
"}\n"
"#regUsername, #regPw, #security, #signuperrorMsg, #MarkedText, #haveAcc{\n"
"    color:#808390;\n"
"    font-family: Poppins;\n"
"}\n"
"\n"
"#regUsername, #regPw, #security{\n"
"    padding-top:25px;\n"
"}\n"
"QLineEdit{\n"
"    height:50px;\n"
"    padding: 1px 15 px;\n"
"    background-color: rgb(42, 43, 48);\n"
"    border: 1px solid rgba(84,86,95,255);\n"
"    border-radius: 10px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-family: Poppins;\n"
"    font-size:15px;\n"
"}\n"
"#SI_buttonSI{\n"
"    background-color: rgb(254, 221, 59);    \n"
"    border-radius:5px;\n"
"    height:50px;\n"
"}\n"
"#SI_checkboxTerm{\n"
"    background-color: rgb(42, 43, 48);\n"
"    color:#808390;\n"
"}\n"
"QComboBox {\n"
"    color: white;                        /* Warna teks combobox */\n"
"    background-color:  rgb(128, 131, 144);           /* Warna latar belakang combobox */\n"
"    border: 1px solid #555555;           /* Warna border combobox */\n"
"    border-radius: 5px;                  /* Membuat sudut rounded */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: white;                        /* Warna teks dropdown */\n"
"    background-color: #333333;           /* Warna latar belakang dropdown */\n"
"    selection-background-color: #fedd3b; /* Warna latar belakang item yang dipilih*/\n"
"    selection-color: black;              /* Warna teks item yang dipilih */\n"
"    border: 1px solid #555555;          /* Warna border dropdown */\n"
"}\n"
"")
        self.signupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signupFrame.setObjectName("signupFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.signupFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.signupHeader = QtWidgets.QLabel(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(13)
        self.signupHeader.setFont(font)
        self.signupHeader.setObjectName("signupHeader")
        self.verticalLayout_4.addWidget(self.signupHeader)
        self.regUsername = QtWidgets.QLabel(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.regUsername.setFont(font)
        self.regUsername.setObjectName("regUsername")
        self.verticalLayout_4.addWidget(self.regUsername)
        self.SI_inputUsername = QtWidgets.QLineEdit(self.signupFrame)
        self.SI_inputUsername.setObjectName("SI_inputUsername")
        self.verticalLayout_4.addWidget(self.SI_inputUsername)
        self.regPw = QtWidgets.QLabel(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.regPw.setFont(font)
        self.regPw.setObjectName("regPw")
        self.verticalLayout_4.addWidget(self.regPw)
        self.SI_inputPassword1 = QtWidgets.QLineEdit(self.signupFrame)
        self.SI_inputPassword1.setStyleSheet("")
        self.SI_inputPassword1.setObjectName("SI_inputPassword1")
        self.verticalLayout_4.addWidget(self.SI_inputPassword1)
        self.SI_inputPassword2 = QtWidgets.QLineEdit(self.signupFrame)
        self.SI_inputPassword2.setObjectName("SI_inputPassword2")
        self.verticalLayout_4.addWidget(self.SI_inputPassword2)
        self.security = QtWidgets.QLabel(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.security.setFont(font)
        self.security.setStyleSheet("")
        self.security.setObjectName("security")
        self.verticalLayout_4.addWidget(self.security)
        self.SI_dropdownSecurity = QtWidgets.QComboBox(self.signupFrame)
        self.SI_dropdownSecurity.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.SI_dropdownSecurity.setFont(font)
        self.SI_dropdownSecurity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SI_dropdownSecurity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SI_dropdownSecurity.setStyleSheet("")
        self.SI_dropdownSecurity.setCurrentText("")
        self.SI_dropdownSecurity.setObjectName("SI_dropdownSecurity")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.setItemText(0, "")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.SI_dropdownSecurity.addItem("")
        self.verticalLayout_4.addWidget(self.SI_dropdownSecurity)
        self.SI_inputSecurity = QtWidgets.QLineEdit(self.signupFrame)
        self.SI_inputSecurity.setObjectName("SI_inputSecurity")
        self.verticalLayout_4.addWidget(self.SI_inputSecurity)
        self.SI_checkboxTerm = QtWidgets.QCheckBox(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.SI_checkboxTerm.setFont(font)
        self.SI_checkboxTerm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SI_checkboxTerm.setStyleSheet("padding-left:7px;")
        self.SI_checkboxTerm.setObjectName("SI_checkboxTerm")
        self.verticalLayout_4.addWidget(self.SI_checkboxTerm)
        self.MarkedText = QtWidgets.QLabel(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.MarkedText.setFont(font)
        self.MarkedText.setObjectName("MarkedText")
        self.verticalLayout_4.addWidget(self.MarkedText)
        self.SI_ErrorMsg = QtWidgets.QLabel(self.signupFrame)
        self.SI_ErrorMsg.setMinimumSize(QtCore.QSize(0, 0))
        self.SI_ErrorMsg.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.SI_ErrorMsg.setFont(font)
        self.SI_ErrorMsg.setStyleSheet("color: rgb(255, 32, 35);")
        self.SI_ErrorMsg.setText("")
        self.SI_ErrorMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SI_ErrorMsg.setObjectName("SI_ErrorMsg")
        self.verticalLayout_4.addWidget(self.SI_ErrorMsg)
        self.SI_buttonSI = QtWidgets.QPushButton(self.signupFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SI_buttonSI.setFont(font)
        self.SI_buttonSI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SI_buttonSI.setObjectName("SI_buttonSI")
        self.verticalLayout_4.addWidget(self.SI_buttonSI)
        self.frame_3 = QtWidgets.QFrame(self.signupFrame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.haveAcc = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.haveAcc.setFont(font)
        self.haveAcc.setStyleSheet("padding:0px;")
        self.haveAcc.setObjectName("haveAcc")
        self.horizontalLayout.addWidget(self.haveAcc)
        self.SI_buttonLogIn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SI_buttonLogIn.setFont(font)
        self.SI_buttonLogIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SI_buttonLogIn.setStyleSheet("")
        self.SI_buttonLogIn.setObjectName("SI_buttonLogIn")
        self.horizontalLayout.addWidget(self.SI_buttonLogIn)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout_5.addWidget(self.signupFrame, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollBar)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.innerstackedWidget.addWidget(self.signupPage)
        self.changePW = QtWidgets.QWidget()
        self.changePW.setStyleSheet("")
        self.changePW.setObjectName("changePW")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.changePW)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.changepwFrame = QtWidgets.QFrame(self.changePW)
        self.changepwFrame.setStyleSheet("#changepwFrame{\n"
"    background-color: rgb(42, 43, 48);\n"
"       padding-left: 15px;      \n"
"       padding-right: 20px;       \n"
"    padding-top: 25px;          \n"
"    padding-bottom: 25px;\n"
"    border-radius: 15px;      \n"
"}\n"
"#frame_5{\n"
"    background-color: rgb(42, 43, 48);\n"
"}\n"
"QLineEdit{\n"
"    height:50px;\n"
"    padding: 1px 15 px;\n"
"    background-color: rgb(42, 43, 48);\n"
"    border: 1px solid rgba(84,86,95,255);\n"
"    border-radius: 10px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-family: Poppins;\n"
"    font-size:15px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(42, 43, 48);\n"
"    padding-left:5px;\n"
"}\n"
"#CP_buttonSavePW{\n"
"    background-color: #FFD700;    \n"
"    border-radius:5px;\n"
"    height:50px;\n"
"}\n"
"#secQuestionLabel, #resetPw, #whatuWaiting{\n"
"    color:#808390;\n"
"    font-family: Poppins;\n"
"}\n"
"#secQuestionLabel, #resetPw{\n"
"    padding-top:25px;\n"
"}\n"
"#CP_buttonLogIn{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(84, 86, 95);\n"
"    border-radius:15px;\n"
"    height:30px;\n"
"}\n"
"QComboBox {\n"
"    color: white;                        /* Warna teks combobox */\n"
"    background-color:rgb(128, 131, 144);           /* Warna latar belakang combobox */\n"
"    border: 1px solid #555555;           /* Warna border combobox */\n"
"    border-radius: 5px;                  /* Membuat sudut rounded */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: white;                        /* Warna teks dropdown */\n"
"    background-color: #333333;           /* Warna latar belakang dropdown */\n"
"    selection-background-color: #fedd3b; /* Warna latar belakang item yang dipilih*/\n"
"    selection-color: black;              /* Warna teks item yang dipilih */\n"
"    border: 1px solid #555555;          /* Warna border dropdown */\n"
"}")
        self.changepwFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.changepwFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.changepwFrame.setObjectName("changepwFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.changepwFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.changepwHeader = QtWidgets.QLabel(self.changepwFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.changepwHeader.setFont(font)
        self.changepwHeader.setObjectName("changepwHeader")
        self.verticalLayout_5.addWidget(self.changepwHeader)
        self.secQuestionLabel = QtWidgets.QLabel(self.changepwFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.secQuestionLabel.setFont(font)
        self.secQuestionLabel.setObjectName("secQuestionLabel")
        self.verticalLayout_5.addWidget(self.secQuestionLabel)
        self.secQuestion_2 = QtWidgets.QComboBox(self.changepwFrame)
        self.secQuestion_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.secQuestion_2.setFont(font)
        self.secQuestion_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.secQuestion_2.setStyleSheet("")
        self.secQuestion_2.setObjectName("secQuestion_2")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.setItemText(0, "")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.secQuestion_2.addItem("")
        self.verticalLayout_5.addWidget(self.secQuestion_2)
        self.CP_inputSecAnswer = QtWidgets.QLineEdit(self.changepwFrame)
        self.CP_inputSecAnswer.setObjectName("CP_inputSecAnswer")
        self.verticalLayout_5.addWidget(self.CP_inputSecAnswer)
        self.resetPw = QtWidgets.QLabel(self.changepwFrame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.resetPw.setFont(font)
        self.resetPw.setObjectName("resetPw")
        self.verticalLayout_5.addWidget(self.resetPw)
        self.CP_inputPassword1 = QtWidgets.QLineEdit(self.changepwFrame)
        self.CP_inputPassword1.setObjectName("CP_inputPassword1")
        self.verticalLayout_5.addWidget(self.CP_inputPassword1)
        self.CP_inputPassword2 = QtWidgets.QLineEdit(self.changepwFrame)
        self.CP_inputPassword2.setObjectName("CP_inputPassword2")
        self.verticalLayout_5.addWidget(self.CP_inputPassword2)
        self.succesMsg = QtWidgets.QLabel(self.changepwFrame)
        self.succesMsg.setMinimumSize(QtCore.QSize(0, 25))
        self.succesMsg.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.succesMsg.setFont(font)
        self.succesMsg.setObjectName("succesMsg")
        self.verticalLayout_5.addWidget(self.succesMsg)
        self.CP_buttonSavePW = QtWidgets.QPushButton(self.changepwFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CP_buttonSavePW.setFont(font)
        self.CP_buttonSavePW.setObjectName("CP_buttonSavePW")
        self.verticalLayout_5.addWidget(self.CP_buttonSavePW)
        self.frame_5 = QtWidgets.QFrame(self.changepwFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.whatuWaiting = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.whatuWaiting.setFont(font)
        self.whatuWaiting.setObjectName("whatuWaiting")
        self.horizontalLayout_4.addWidget(self.whatuWaiting)
        self.CP_buttonLogIn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CP_buttonLogIn.setFont(font)
        self.CP_buttonLogIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CP_buttonLogIn.setObjectName("CP_buttonLogIn")
        self.horizontalLayout_4.addWidget(self.CP_buttonLogIn)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.gridLayout_6.addWidget(self.changepwFrame, 0, 0, 1, 1)
        self.innerstackedWidget.addWidget(self.changePW)
        self.gridLayout_2.addWidget(self.innerstackedWidget, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.loginsignup)
        self.inputData = QtWidgets.QWidget()
        self.inputData.setObjectName("inputData")
        self.label_3 = QtWidgets.QLabel(self.inputData)
        self.label_3.setGeometry(QtCore.QRect(204, 165, 521, 361))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.inputData)
        self.showData = QtWidgets.QWidget()
        self.showData.setObjectName("showData")
        self.label_4 = QtWidgets.QLabel(self.showData)
        self.label_4.setGeometry(QtCore.QRect(250, 300, 461, 161))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.showData)
        self.chatBot = QtWidgets.QWidget()
        self.chatBot.setObjectName("chatBot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.chatBot)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.frame_7 = QtWidgets.QFrame(self.chatBot)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.chatHandle = QtWidgets.QScrollArea(self.frame_7)
        self.chatHandle.setStyleSheet("border: none;")
        self.chatHandle.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.chatHandle.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chatHandle.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.chatHandle.setWidgetResizable(True)
        self.chatHandle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.chatHandle.setObjectName("chatHandle")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 781, 562))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.chat1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat1.sizePolicy().hasHeightForWidth())
        self.chat1.setSizePolicy(sizePolicy)
        self.chat1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat1.setObjectName("chat1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.chat1)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.chat1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"padding-left: 50px;\n"
"padding-right: 25px;\n"
"\n"
"border-top-right-radius: 25px;\n"
"border-bottom-right-radius: 25px;")
        self.label_8.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.chat1)
        self.chatHandle.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.chatHandle)
        self.userChatInput = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userChatInput.sizePolicy().hasHeightForWidth())
        self.userChatInput.setSizePolicy(sizePolicy)
        self.userChatInput.setAutoFillBackground(False)
        self.userChatInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 15px;")
        self.userChatInput.setText("")
        self.userChatInput.setObjectName("userChatInput")
        self.verticalLayout_8.addWidget(self.userChatInput)
        self.horizontalLayout_6.addWidget(self.frame_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.chatBot)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.profile)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_12.setContentsMargins(100, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.profile)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.horizontalLayout_9.addWidget(self.frame_11)
        self.line = QtWidgets.QFrame(self.frame_10)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.horizontalLayout_9.addWidget(self.frame_12)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_13 = QtWidgets.QFrame(self.profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.label_13 = QtWidgets.QLabel(self.frame_14)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        spacerItem9 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_14.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_15)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_14.addWidget(self.frame_15)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.profile)
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.about)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem11)
        self.frame_4 = QtWidgets.QFrame(self.about)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #808390")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem13)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_5.addWidget(self.frame_6)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_6.addWidget(self.frame_4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.about)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.mainMenu, 0, 1, 1, 1)
        self.menuBar = QtWidgets.QWidget(self.centralwidget)
        self.menuBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.menuBar.setObjectName("menuBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuBar)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem17)
        self.homeButton = QtWidgets.QPushButton(self.menuBar)
        self.homeButton.setMinimumSize(QtCore.QSize(0, 30))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("border: none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI\\../Assets/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout.addWidget(self.homeButton)
        self.loginButton = QtWidgets.QPushButton(self.menuBar)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("border: none;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI\\../Assets/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon2)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.inputdataButton = QtWidgets.QPushButton(self.menuBar)
        self.inputdataButton.setMinimumSize(QtCore.QSize(0, 30))
        self.inputdataButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inputdataButton.setStyleSheet("border: none;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI\\../Assets/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inputdataButton.setIcon(icon3)
        self.inputdataButton.setObjectName("inputdataButton")
        self.verticalLayout.addWidget(self.inputdataButton)
        self.showdatabutton = QtWidgets.QPushButton(self.menuBar)
        self.showdatabutton.setMinimumSize(QtCore.QSize(0, 30))
        self.showdatabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showdatabutton.setStyleSheet("border: none;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI\\../Assets/analyze.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showdatabutton.setIcon(icon4)
        self.showdatabutton.setObjectName("showdatabutton")
        self.verticalLayout.addWidget(self.showdatabutton)
        self.chatbotButton = QtWidgets.QPushButton(self.menuBar)
        self.chatbotButton.setMinimumSize(QtCore.QSize(0, 30))
        self.chatbotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chatbotButton.setStyleSheet("border: none;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("UI\\../Assets/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatbotButton.setIcon(icon5)
        self.chatbotButton.setObjectName("chatbotButton")
        self.verticalLayout.addWidget(self.chatbotButton)
        self.aboutButton = QtWidgets.QPushButton(self.menuBar)
        self.aboutButton.setMinimumSize(QtCore.QSize(0, 30))
        self.aboutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutButton.setStyleSheet("border: none;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("UI\\../Assets/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon6)
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout.addWidget(self.aboutButton)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.profileButton = QtWidgets.QPushButton(self.menuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileButton.sizePolicy().hasHeightForWidth())
        self.profileButton.setSizePolicy(sizePolicy)
        self.profileButton.setMinimumSize(QtCore.QSize(50, 50))
        self.profileButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileButton.setStyleSheet("border: none;")
        self.profileButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("UI\\../Assets/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileButton.setIcon(icon7)
        self.profileButton.setObjectName("profileButton")
        self.verticalLayout.addWidget(self.profileButton)
        self.gridLayout_3.addWidget(self.menuBar, 0, 0, 1, 1)
        Master.setCentralWidget(self.centralwidget)

        self.retranslateUi(Master)
        self.stackedWidget.setCurrentIndex(6)
        self.innerstackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Master)

    def retranslateUi(self, Master):
        _translate = QtCore.QCoreApplication.translate
        Master.setWindowTitle(_translate("Master", "Personal Finance Manager"))
        self.label.setText(_translate("Master", "<html><head/><body><p>Personal Finance</p><p>Manager</p></body></html>"))
        self.label_9.setText(_translate("Master", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">&quot;The journey of a thousand miles begins with one step.&quot; </span></p><p align=\"center\"><span style=\" font-style:italic;\">— Lao Tzu</span></p><p align=\"center\"><br/></p><p>Hi, User!</p><p>It is Monday, September 2nd 2024. What would you like to do?</p></body></html>"))
        self.username.setText(_translate("Master", "Username"))
        self.password.setText(_translate("Master", "Password"))
        self.LI_inputUsername.setPlaceholderText(_translate("Master", "Please enter your username..."))
        self.LI_inputPassword.setPlaceholderText(_translate("Master", "Please enter yout password..."))
        self.LI_buttonLI.setText(_translate("Master", "Log In"))
        self.loginHeader.setText(_translate("Master", "<html><head/><body><p><span style=\" font-size:20pt; color:#fedd3b;\">Take control of your finances.</span></p><p><span style=\" font-size:20pt; color:#808390;\">Log in to your PFM account</span></p></body></html>"))
        self.LI_buttonForgetPassword.setText(_translate("Master", "Forgot Password?"))
        self.LI_noAcc.setText(_translate("Master", "Don\'t Have an Account Yet?"))
        self.LI_buttonSignIn.setText(_translate("Master", "Create"))
        self.signupHeader.setText(_translate("Master", "<html><head/><body><p><span style=\" font-size:20pt; color:#fedd3b;\">Build your wealth.</span></p><p><span style=\" font-size:20pt; color:#808390;\">Create your PFM account</span></p></body></html>"))
        self.regUsername.setText(_translate("Master", "<html><head/><body><p>Username<span style=\" color:#ea0003;\">*</span></p></body></html>"))
        self.SI_inputUsername.setPlaceholderText(_translate("Master", "Create your username..."))
        self.regPw.setText(_translate("Master", "<html><head/><body><p>Password<span style=\" color:#ea0003;\">*</span></p></body></html>"))
        self.SI_inputPassword1.setPlaceholderText(_translate("Master", "Create your password..."))
        self.SI_inputPassword2.setPlaceholderText(_translate("Master", "Re-enter your password..."))
        self.security.setText(_translate("Master", "<html><head/><body><p>Security<span style=\" color:#ea0003;\">*</span></p></body></html>"))
        self.SI_dropdownSecurity.setItemText(1, _translate("Master", "   Birthplace"))
        self.SI_dropdownSecurity.setItemText(2, _translate("Master", "   Favorite book"))
        self.SI_dropdownSecurity.setItemText(3, _translate("Master", "   Favorite color"))
        self.SI_dropdownSecurity.setItemText(4, _translate("Master", "   Favorite food"))
        self.SI_dropdownSecurity.setItemText(5, _translate("Master", "   Favorite movie"))
        self.SI_dropdownSecurity.setItemText(6, _translate("Master", "   Favorite sport"))
        self.SI_dropdownSecurity.setItemText(7, _translate("Master", "   Favorite band"))
        self.SI_dropdownSecurity.setItemText(8, _translate("Master", "   Pet\'s name"))
        self.SI_inputSecurity.setPlaceholderText(_translate("Master", "Write your answer..."))
        self.SI_checkboxTerm.setText(_translate("Master", "I accept the Terms of Service and Privacy Policy"))
        self.MarkedText.setText(_translate("Master", "Fields marked with (*) are requierd."))
        self.SI_buttonSI.setText(_translate("Master", "Sign up"))
        self.haveAcc.setText(_translate("Master", "Already Have an Account?"))
        self.SI_buttonLogIn.setText(_translate("Master", "Log in"))
        self.changepwHeader.setText(_translate("Master", "<html><head/><body><p><span style=\" font-size:20pt; color:#fedd3b;\">Protect your finances.</span></p><p><span style=\" font-size:20pt; color:#808390;\">Enhance your protection.</span></p></body></html>"))
        self.secQuestionLabel.setText(_translate("Master", "Security Question"))
        self.secQuestion_2.setItemText(1, _translate("Master", "   Birthplace"))
        self.secQuestion_2.setItemText(2, _translate("Master", "   Favorite book"))
        self.secQuestion_2.setItemText(3, _translate("Master", "   Favorite color"))
        self.secQuestion_2.setItemText(4, _translate("Master", "   Favorite food"))
        self.secQuestion_2.setItemText(5, _translate("Master", "   Favorite movie"))
        self.secQuestion_2.setItemText(6, _translate("Master", "   Favorite sport"))
        self.secQuestion_2.setItemText(7, _translate("Master", "   Favorite band"))
        self.secQuestion_2.setItemText(8, _translate("Master", "   Pet\'s name"))
        self.CP_inputSecAnswer.setPlaceholderText(_translate("Master", "Write your answer..."))
        self.resetPw.setText(_translate("Master", "Reset Password"))
        self.CP_inputPassword1.setPlaceholderText(_translate("Master", "Create your new password..."))
        self.CP_inputPassword2.setPlaceholderText(_translate("Master", "Re-enter your new password..."))
        self.succesMsg.setText(_translate("Master", "<html><head/><body><p align=\"right\"><span style=\" color:#2a2b30;\">*Passwords don\'t match</span></p></body></html>"))
        self.CP_buttonSavePW.setText(_translate("Master", "Save"))
        self.whatuWaiting.setText(_translate("Master", "What Are You Waiting For?"))
        self.CP_buttonLogIn.setText(_translate("Master", "Back to Log In"))
        self.label_3.setText(_translate("Master", "Input Data"))
        self.label_4.setText(_translate("Master", "Show Data"))
        self.label_5.setText(_translate("Master", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Google\'s AI</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; color:#fedd3b;\">Gemini</span></p></body></html>"))
        self.label_8.setText(_translate("Master", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et commodo sem. Integer vehicula dui erat, non vulputate turpis tincidunt quis. Vestibulum ut odio sagittis, viverra magna a, pellentesque dolor. Duis varius enim id turpis efficitur molestie. Donec ultrices, purus nec maximus finibus, diam nisl sollicitudin purus, et condimentum nisi purus at mi. Proin velit felis, porttitor at magna et, accumsan pulvinar nunc. Curabitur feugiat imperdiet ligula ac euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit."))
        self.userChatInput.setPlaceholderText(_translate("Master", "Ask us anything..."))
        self.label_11.setText(_translate("Master", "Atlas"))
        self.label_6.setText(_translate("Master", "Monday, September 1st 2024 - Tuesday, September 2nd 2024"))
        self.label_12.setText(_translate("Master", "<html><head/><body><p>Username</p><p>Date Created</p><p>Date Updated</p><p>Balance</p><p>Transactions Uploaded</p></body></html>"))
        self.label_14.setText(_translate("Master", "<html><head/><body><p>Sigma</p><p>Monday, September 1st 2024</p><p>Tuesday, September 2nd 2024</p><p>Rp. 1.000.000</p><p>17</p></body></html>"))
        self.label_13.setText(_translate("Master", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">We’re grateful that you’ve entrusted us with your financial journey. Managing your finances is a significant step towards achieving your goals, and we’re here to support you every step of the way.</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Master", "Change Password"))
        self.pushButton.setText(_translate("Master", "Log Out"))
        self.label_2.setText(_translate("Master", "<html><head/><body><p><span style=\" color:#fedd3b;\">About Us</span></p><p>Who We Are and What We Do</p></body></html>"))
        self.label_7.setText(_translate("Master", "Personal Finance Manager is designed to empower you to take control of your financial life. It offers a comprehensive, easy-to-use platform for tracking income, expenses, and savings, enabling you to make informed financial decisions. Whether you\'re planning a budget, saving for a goal, or simply trying to understand where your money goes, this tool is here to help. By visualizing your financial data, setting clear goals, and monitoring your progress, you can build a more secure and prosperous future.\n"
"\n"
"This app was created by Jonathan Edward, Davin, and Farhan as part of the requirements for the Control Laboratory Assistant program at FTUI. The project repository is available on GitHub."))
        self.homeButton.setText(_translate("Master", " Home"))
        self.loginButton.setText(_translate("Master", " Login"))
        self.inputdataButton.setText(_translate("Master", " Upload"))
        self.showdatabutton.setText(_translate("Master", " Analyze"))
        self.chatbotButton.setText(_translate("Master", " Chatbot"))
        self.aboutButton.setText(_translate("Master", " About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Master = QtWidgets.QMainWindow()
    ui = Ui_Master()
    ui.setupUi(Master)
    Master.show()
    sys.exit(app.exec_())
